### ISSUE TITLE
Image zooming not working in Microsft Edge and Firefox

### ISSUE THREAD

**Issue by yf508** [digital-york/arch1_search#27]
Jonathan reported on 10 Nov 2020

If I click on a result, and then on 'Click here to enlarge', all I get is an empty black window? I've tried it in Firefox and Edge, with the same result.

**Comment by Jimadine** [comment]
This is broken across all browsers.

Looks like the URL request wasn't properly constructed: `https://dlib.york.ac.uk/cgi-bin/iipsrv.fcgi?DeepZoom=.dzi`
Should be something like `https://dlib.york.ac.uk/cgi-bin/iipsrv.fcgi?DeepZoom=/usr/digilib-webdocs/digilibImages/HOA/current/A/20160104/Abp_Reg_11_0491.jp2_files/13/6_13.jpg`
