### ISSUE TITLE
issues with dates

### ISSUE THREAD

**Issue by yf508** [digital-york/arch1_search#40]
![image](https://user-images.githubusercontent.com/437701/108699880-bceb0980-74fd-11eb-8e96-74f890fde618.png)

DATES are not functioning correctly. ‘Document date’ in many entries appears blank when it should not. Example: [Reg 11, f. 118v entry 4](https://archbishopsregisters.york.ac.uk/browse/registers?entry_no=4&folio=287&register_id=xw42n925d#entries) (see above).

**Comment by yf508** [comment]
Helen also reported on 19 Feb 2021:

I've just spotted something else a bit odd - no dates are displaying in around folios 105-108 of Reg 11, even though they've been input into the tool. I haven't done any wider checking, though.

**Comment by paluchas** [comment]
@yf508 I cannot find an example with the issue for my testing. What is the original search phrase?

**Comment by yf508** [comment]
@paluchas It's highlighted in the screen dump, or you can simply use 'Conisbrough'

**Comment by paluchas** [comment]
Tested and it works.
